"""added user, challenge, wish list and additional relationships

Revision ID: 09c62dadfa6c
Revises: c200d3ed0557
Create Date: 2019-11-16 01:06:30.303268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c62dadfa6c'
down_revision = 'c200d3ed0557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pass_hash', sa.String(length=64), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wish_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('full_description', sa.String(), nullable=True),
    sa.Column('brief_description', sa.String(), nullable=True),
    sa.Column('earn_amount', sa.Numeric(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', 'insane', name='challengedifficulty'), nullable=True),
    sa.Column('sub_category_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_category_fk'], ['sub_category.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wish_list_to_challenge',
    sa.Column('wish_list_fk', sa.Integer(), nullable=False),
    sa.Column('challenge_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_fk'], ['challenge.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wish_list_fk'], ['wish_list.id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_unique_constraint(None, 'category', ['name'])
    op.add_column('item', sa.Column('description', sa.String(), nullable=True))
    op.add_column('item', sa.Column('user_fk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item', 'user', ['user_fk'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(None, 'sub_category', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_category', type_='unique')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'user_fk')
    op.drop_column('item', 'description')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_table('wish_list_to_challenge')
    op.drop_table('challenge')
    op.drop_table('wish_list')
    op.drop_table('user')
    # ### end Alembic commands ###
