"""added user to challenge relationship

Revision ID: 118cfc734d6b
Revises: f98ac957bcd9
Create Date: 2019-11-16 14:50:37.769366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118cfc734d6b'
down_revision = 'f98ac957bcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_list_to_challenge', sa.Column('user_fk', sa.Integer(), nullable=False))
    op.alter_column('wish_list_to_challenge', 'wish_list_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'wish_list_to_challenge', 'user', ['user_fk'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wish_list_to_challenge', type_='foreignkey')
    op.alter_column('wish_list_to_challenge', 'wish_list_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('wish_list_to_challenge', 'user_fk')
    # ### end Alembic commands ###
