"""working on challenge progress

Revision ID: 2abb53a90d7c
Revises: 4c326a11ebaf
Create Date: 2019-11-17 02:46:52.692715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abb53a90d7c'
down_revision = '4c326a11ebaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_list_to_challenge', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_list_to_challenge', 'created_at')
    # ### end Alembic commands ###
