"""removed unique name challenge

Revision ID: 4c326a11ebaf
Revises: 9e04ca8f19e8
Create Date: 2019-11-17 00:46:36.478341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c326a11ebaf'
down_revision = '9e04ca8f19e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('challenge_name_key', 'challenge', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('challenge_name_key', 'challenge', ['name'])
    # ### end Alembic commands ###
