"""removed wishlist item unique name constraint

Revision ID: 9e04ca8f19e8
Revises: 80f80413d24c
Create Date: 2019-11-16 16:50:49.691635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e04ca8f19e8'
down_revision = '80f80413d24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wish_list_name_key', 'wish_list', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wish_list_name_key', 'wish_list', ['name'])
    # ### end Alembic commands ###
