"""changed amount to numeric, removed unique constraint on sub category name

Revision ID: f98ac957bcd9
Revises: 09c62dadfa6c
Create Date: 2019-11-16 10:55:56.751766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98ac957bcd9'
down_revision = '09c62dadfa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sub_category_name_key', 'sub_category', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sub_category_name_key', 'sub_category', ['name'])
    # ### end Alembic commands ###
